### ISSUE TITLE
Shipper Checkbox is too big

### ISSUE THREAD

**Issue by JoaquimEsteves** [yoctu/redspher-react-components#44]
According to our lovely design docs, the SVG should be 10px high/wide.

Because of some Material-UI root injection crap it ended up having a width/height of 1em.

![image](https://user-images.githubusercontent.com/14824338/133617824-999de46a-bcc2-4711-be7c-f7416c900504.png)

```css
.MuiSvgIcon-root {
	fill: currentColor;
	width: 1em;
	height: 1em;
	display: inline-block;
	font-size: 1.5rem;
	transition: fill 200ms cubic-bezier(0.4, 0, 0.2, 1) 0ms;
	flex-shrink: 0;
	-moz-user-select: none;
}
```

Could be related to the theming and all of the overriding
